### ISSUE TITLE
为啥我用cocoa pods安装时说没有这个库 啊

### ISSUE THREAD

**Issue by Elgins** [LeoMobileDeveloper/ParallexBanner#1]
难道是因为还没有收录么,还是我的pod有问题,咋搞

**Comment by LeoMobileDeveloper** [comment]
这个库是iOS 8+的，试试在Podfile最上面添加 platform :ios, ‘8.0’。还是不行的话，终端执行 pod setup来更新本地Cocoa Pod缓存，然后在pod install。我在我的电脑上试了下，是可以安装的 @Elgins
